import { Empire, ResourceCost } from '@game/shared';

/**
 * Service for managing empire resources
 */
export class ResourceService {
  constructor(
    private readonly empire: Empire
  ) {}

  /**
   * Get the current resources of the empire
   */
  public getCurrentResources(): ResourceCost {
    return this.empire.resources;
  }

  /**
   * Check if the empire can afford a cost
   */
  public canAfford(cost: ResourceCost): boolean {
    const current = this.getCurrentResources();
    return current.credits >= (cost.credits || 0);
  }

  /**
   * Deduct resources from the empire
   */
  public deductResources(cost: ResourceCost): void {
    this.empire.resources.credits -= (cost.credits || 0);
  }

  /**
   * Add resources to the empire
   */
  public addResources(cost: ResourceCost): void {
    this.empire.resources.credits += (cost.credits || 0);
  }

  /**
   * Calculate the credits per hour for an empire
   */
  public calculateCreditsPerHour(): number {
    // Credits generated by economy
    return 100; // Placeholder - implement real calculation
  }
}