name: 🐛 Bug Report
description: Report a bug or issue with Attrition
title: "[BUG] "
labels: ["type:bug", "status:triage-needed", "priority:medium"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## 🐛 Bug Report
        
        Thank you for taking the time to report a bug! This information helps us improve Attrition.
        
        **Before submitting:** Please check if this issue already exists in our [issue tracker](../../../issues).

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical (Application crashes, data loss, security issue)
        - High (Major feature broken, blocking workflow)
        - Medium (Minor feature issue, workaround available)
        - Low (Cosmetic issue, enhancement)
      default: 2
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Step-by-step instructions to reproduce the bug
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe what should have happened...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Which platform are you using?
      options:
        - Windows
        - macOS
        - Linux (Ubuntu/Debian)
        - Linux (Fedora/RHEL)
        - Linux (Arch)
        - Linux (Other)
        - Multiple platforms
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Attrition Version
      description: What version of Attrition are you running?
      placeholder: e.g., 1.0.0-beta.1
    validations:
      required: true

  - type: dropdown
    id: frequency
    attributes:
      label: Frequency
      description: How often does this bug occur?
      options:
        - Always (100% of the time)
        - Often (75% of the time)
        - Sometimes (50% of the time)
        - Rarely (25% of the time)
        - Once (only happened once)
      default: 2
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment Details
      description: Additional environment information
      placeholder: |
        OS Version: 
        Architecture: (x64/ARM64)
        Memory: 
        Any relevant hardware/software details:
      render: text

  - type: textarea
    id: logs
    attributes:
      label: Error Logs
      description: Any error messages or logs related to this bug
      placeholder: Paste error messages, stack traces, or log entries here...
      render: text

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain the problem
      placeholder: Drag and drop images here or use the upload button...

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context about the problem
      placeholder: Add any other context about the problem here...

  - type: dropdown
    id: impact
    attributes:
      label: Impact on Users
      description: How many users might be affected by this bug?
      options:
        - All users
        - Most users
        - Some users
        - Few users
        - Just me
      default: 2

  - type: checkboxes
    id: checklist
    attributes:
      label: Submission Checklist
      description: Please confirm the following
      options:
        - label: I have searched for existing issues that describe this bug
          required: true
        - label: I have included steps to reproduce the bug
          required: true
        - label: I have included my environment details
          required: true
        - label: I have included error logs (if applicable)
          required: false

  - type: markdown
    attributes:
      value: |
        ---
        
        **Thank you for your bug report!** 
        
        Our team will review this issue and respond according to our [SLA guidelines](../../docs/sla-guidelines.md):
        - **Critical**: 2-4 hours
        - **High**: 4-8 hours  
        - **Medium**: 1 business day
        - **Low**: 2 business days
