"use strict";
// Units catalog and helpers for Phase A (tech-gated).
// Values set to match provided screenshots for Units tab. UI reads these canonically.
Object.defineProperty(exports, "__esModule", { value: true });
exports.unitsCatalog = void 0;
exports.getUnitsList = getUnitsList;
exports.getUnitSpec = getUnitSpec;
// Catalog populated per screenshots
exports.unitsCatalog = {
    fighter: {
        key: 'fighter',
        name: 'Fighter',
        creditsCost: 5,
        drive: 'Inter',
        weapon: 'laser',
        attack: 2,
        armour: 2,
        shield: 0,
        hangar: -1,
        speed: 0,
        requiredShipyardLevel: 1,
        techPrereqs: [{ key: 'laser', level: 1 }],
        description: 'Good fighting unit against unshielded units.',
    },
    bomber: {
        key: 'bomber',
        name: 'Bomber',
        creditsCost: 10,
        drive: 'Inter',
        weapon: 'missiles',
        attack: 4,
        armour: 2,
        shield: 0,
        hangar: -1,
        speed: 0,
        requiredShipyardLevel: 2,
        techPrereqs: [{ key: 'missiles', level: 1 }],
        description: 'Good fighting unit against unshielded and low shield units.',
    },
    heavy_bomber: {
        key: 'heavy_bomber',
        name: 'Heavy Bomber',
        creditsCost: 30,
        drive: 'Inter',
        weapon: 'plasma',
        attack: 10,
        armour: 4,
        shield: 0,
        hangar: -2,
        speed: 0,
        requiredShipyardLevel: 3,
        techPrereqs: [{ key: 'plasma', level: 14 }],
        description: 'Good fighting unit against medium shielded units.',
    },
    ion_bomber: {
        key: 'ion_bomber',
        name: 'Ion Bomber',
        creditsCost: 60,
        drive: 'Inter',
        weapon: 'ion',
        attack: 12,
        armour: 4,
        shield: 1,
        hangar: -2,
        speed: 3,
        techPrereqs: [
            { key: 'ion', level: 10 },
            { key: 'shielding', level: 10 },
        ],
        description: 'Good against high shielded units, 50% power cross shields.',
    },
    corvette: {
        key: 'corvette',
        name: 'Corvette',
        creditsCost: 20,
        drive: 'Stellar',
        weapon: 'laser',
        attack: 4,
        armour: 4,
        shield: 0,
        hangar: 0,
        speed: 10,
        requiredShipyardLevel: 4,
        techPrereqs: [
            { key: 'laser', level: 2 },
            { key: 'stellar_drive', level: 1 },
            { key: 'armour', level: 2 },
        ],
        description: 'Very fast unit, good against unshielded units.',
    },
    recycler: {
        key: 'recycler',
        name: 'Recycler',
        creditsCost: 30,
        drive: 'Stellar*', // annotated as per screenshot
        weapon: 'laser',
        attack: 2,
        armour: 2,
        shield: 0,
        hangar: 0,
        speed: 8,
        requiredShipyardLevel: 5,
        techPrereqs: [
            { key: 'laser', level: 1 },
            { key: 'stellar_drive', level: 1 },
            { key: 'armour', level: 2 },
        ],
        description: 'Can collect debris and convert them into credits.',
    },
    destroyer: {
        key: 'destroyer',
        name: 'Destroyer',
        creditsCost: 40,
        drive: 'Stellar',
        weapon: 'plasma',
        attack: 8,
        armour: 8,
        shield: 0,
        hangar: 0,
        speed: 8,
        requiredShipyardLevel: 6,
        techPrereqs: [
            { key: 'plasma', level: 1 },
            { key: 'stellar_drive', level: 2 },
            { key: 'armour', level: 6 },
        ],
        description: 'Fast unit, good against low shielded units.',
    },
    frigate: {
        key: 'frigate',
        name: 'Frigate',
        creditsCost: 80,
        drive: 'Stellar',
        weapon: 'missiles',
        attack: 12,
        armour: 12,
        shield: 0,
        hangar: 4,
        speed: 6,
        requiredShipyardLevel: 8,
        techPrereqs: [
            { key: 'missiles', level: 6 },
            { key: 'stellar_drive', level: 4 },
            { key: 'armour', level: 8 },
        ],
        description: 'Versatile unit, has 4 hangar space.',
    },
    ion_frigate: {
        key: 'ion_frigate',
        name: 'Ion Frigate',
        creditsCost: 120,
        drive: 'Stellar',
        weapon: 'ion',
        attack: 14,
        armour: 12,
        shield: 1,
        hangar: 4,
        speed: 6,
        requiredShipyardLevel: 8,
        techPrereqs: [
            { key: 'ion', level: 10 },
            { key: 'stellar_drive', level: 4 },
            { key: 'armour', level: 8 },
            { key: 'shielding', level: 10 },
        ],
        description: 'Versatile unit, 50% power cross shields.',
    },
    scout_ship: {
        key: 'scout_ship',
        name: 'Scout Ship',
        creditsCost: 40,
        drive: 'Warp',
        weapon: 'laser',
        attack: 1,
        armour: 2,
        shield: 0,
        hangar: 0,
        speed: 12,
        requiredShipyardLevel: 4,
        techPrereqs: [{ key: 'warp_drive', level: 1 }],
        description: 'Faster ship, good for scouting.',
    },
    outpost_ship: {
        key: 'outpost_ship',
        name: 'Outpost Ship',
        creditsCost: 100,
        drive: 'Warp',
        weapon: 'laser',
        attack: 2,
        armour: 4,
        shield: 0,
        hangar: 0,
        speed: 4,
        requiredShipyardLevel: 8,
        techPrereqs: [{ key: 'warp_drive', level: 1 }],
        description: 'Warp unit that can build a new base.',
    },
    cruiser: {
        key: 'cruiser',
        name: 'Cruiser',
        creditsCost: 200,
        drive: 'Warp',
        weapon: 'plasma',
        attack: 24,
        armour: 24,
        shield: 2,
        hangar: 4,
        speed: 5,
        requiredShipyardLevel: 10,
        techPrereqs: [
            { key: 'plasma', level: 4 },
            { key: 'warp_drive', level: 2 },
            { key: 'armour', level: 10 },
            { key: 'shielding', level: 2 },
        ],
        description: 'Versatile unit, good for long range action and escort.',
    },
    carrier: {
        key: 'carrier',
        name: 'Carrier',
        creditsCost: 400,
        drive: 'Warp',
        weapon: 'missiles',
        attack: 12,
        armour: 24,
        shield: 2,
        hangar: 80,
        speed: 5,
        requiredShipyardLevel: 12,
        techPrereqs: [
            { key: 'missiles', level: 6 },
            { key: 'warp_drive', level: 4 },
            { key: 'armour', level: 10 },
            { key: 'shielding', level: 2 },
        ],
        description: 'Unit with 80 hangar spaces.',
    },
    heavy_cruiser: {
        key: 'heavy_cruiser',
        name: 'Heavy Cruiser',
        creditsCost: 500,
        drive: 'Warp',
        weapon: 'plasma',
        attack: 48,
        armour: 48,
        shield: 4,
        hangar: 8,
        speed: 4,
        requiredShipyardLevel: 12,
        techPrereqs: [
            { key: 'plasma', level: 6 },
            { key: 'warp_drive', level: 4 },
            { key: 'armour', level: 12 },
            { key: 'shielding', level: 4 },
        ],
        description: 'Strong unit, good against large units.',
    },
    battleship: {
        key: 'battleship',
        name: 'Battleship',
        creditsCost: 2000,
        drive: 'Warp',
        weapon: 'ion',
        attack: 168,
        armour: 128,
        shield: 10,
        hangar: 40,
        speed: 4,
        requiredShipyardLevel: 16,
        techPrereqs: [
            { key: 'ion', level: 6 },
            { key: 'warp_drive', level: 8 },
            { key: 'armour', level: 16 },
            { key: 'shielding', level: 8 },
        ],
        description: 'Strong unit, good against large units.',
    },
    fleet_carrier: {
        key: 'fleet_carrier',
        name: 'Fleet Carrier',
        creditsCost: 2500,
        drive: 'Warp',
        weapon: 'ion',
        attack: 64,
        armour: 96,
        shield: 8,
        hangar: 500,
        speed: 4,
        requiredShipyardLevel: 16,
        techPrereqs: [
            { key: 'ion', level: 4 },
            { key: 'warp_drive', level: 8 },
            { key: 'armour', level: 14 },
            { key: 'shielding', level: 6 },
        ],
        description: 'Large carrier with 500 hangar spaces.',
    },
    dreadnought: {
        key: 'dreadnought',
        name: 'Dreadnought',
        creditsCost: 10000,
        drive: 'Warp',
        weapon: 'photon',
        attack: 756,
        armour: 512,
        shield: 20,
        hangar: 200,
        speed: 3,
        requiredShipyardLevel: 20,
        requiredOrbitalShipyardLevel: 1,
        techPrereqs: [
            { key: 'photon', level: 6 },
            { key: 'warp_drive', level: 12 },
            { key: 'armour', level: 20 },
            { key: 'shielding', level: 10 },
        ],
        description: 'Very strong combat unit.',
    },
    titan: {
        key: 'titan',
        name: 'Titan',
        creditsCost: 50000,
        drive: 'Warp',
        weapon: 'disruptor',
        attack: 3500,
        armour: 2048,
        shield: 30,
        hangar: 1000,
        speed: 3,
        requiredShipyardLevel: 22,
        requiredOrbitalShipyardLevel: 3,
        techPrereqs: [
            { key: 'disruptor', level: 6 },
            { key: 'warp_drive', level: 14 },
            { key: 'armour', level: 22 },
            { key: 'shielding', level: 14 },
        ],
        description: 'Very large and strong combat unit.',
    },
    leviathan: {
        key: 'leviathan',
        name: 'Leviathan',
        creditsCost: 200000,
        drive: 'Warp',
        weapon: 'photon',
        attack: 10000,
        armour: 6600,
        shield: 40,
        hangar: 4000,
        speed: 2,
        requiredShipyardLevel: 24,
        requiredOrbitalShipyardLevel: 5,
        techPrereqs: [
            { key: 'photon', level: 12 },
            { key: 'warp_drive', level: 18 },
            { key: 'armour', level: 24 },
            { key: 'shielding', level: 16 },
        ],
        description: 'Huge combat unit, gives +5% power and armour to fleet.',
    },
    death_star: {
        key: 'death_star',
        name: 'Death Star',
        creditsCost: 500000,
        drive: 'Warp',
        weapon: 'disruptor',
        attack: 26500,
        armour: 14000,
        shield: 60,
        hangar: 10000,
        speed: 2,
        requiredShipyardLevel: 26,
        requiredOrbitalShipyardLevel: 7,
        techPrereqs: [
            { key: 'disruptor', level: 10 },
            { key: 'warp_drive', level: 20 },
            { key: 'armour', level: 26 },
            { key: 'shielding', level: 18 },
        ],
        description: 'Biggest unit, can’t use jump gates, gives +10% power and armour to fleet.',
    },
};
function getUnitsList() {
    return Object.values(exports.unitsCatalog);
}
function getUnitSpec(key) {
    return exports.unitsCatalog[key];
}
